kind: pipeline
name: shop

workspace:
  base: /root
  path: web/shop/

steps:
  - name: build
    image: golang
    commands:
      - pwd
      - go env
      - go version
      - go build
    environment:
      GOPROXY: https://goproxy.io

  - name: publish
    image: plugins/docker
    commands:
      - 'docker login -u $${USERNAME} -p $${PASSWORD}'
      - 'docker build -f Dockerfile -t meichaofan/shop:latest .'
      - 'docker push meichaofan/shop:latest'
    dockerfile: ./Dockerfile
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    host: $HOST
    username: $USERNAME
    port: $PORT
    secrets: $RSA
    script:
      - cd /root/web/shop
      - docker-compose pull meichaofan/shop
      - docker-compose up
    environment:
      HOST:
        from_secret: host_ip
      USERNAME:
        from_secret: host_username
      PORT:
        from_secret: host_port
      RSA:
        from_secret: ssh_key


triger:
  branch:
    - master
  event:
    - push
