kind: pipeline
name: shop

workspace:
  base: /root
  path: web/shop/

steps:
  - name: build
    image: golang
    commands:
      - go build
    environment:
      GOPROXY: https://goproxy.io

  - name: publish
    image: plugins/docker
    settings:
      registry: https://index.docker.io/v1/
      repo: meichaofan/shop
      dockerfile: ./Dockerfile
      Username:
        from_secret: docker_username
      Password:
        from_secret: docker_password
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      ssh_username:
        from_secret: ssh_username
      ssh_password:
        from_secret: ssh_password
      port:
        from_secret: ssh_port
    script:
      - cd /root/web/shop
      - docker-compose pull meichaofan/shop
      - docker-compose up -d

triger:
  branch:
    - master
  event:
    - push
