kind: pipeline
name: shop

workspace:
  base: /root
  path: web/shop/

steps:
  - name: build
    image: golang
    commands:
      - go build
    environment:
      GOPROXY: https://goproxy.io

  - name: publish
    image: plugins/docker
    settings:
      registry: https://index.docker.io/v1/
      repo: meichaofan/shop
      dockerfile: ./Dockerfile
      Username:
        from_secret: docker_username
      Password:
        from_secret: docker_password
      tags: latest

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: host_ip
      username:
        from_secret: host_username
      port:
        from_secret: host_port
      ssh-key:
        from_secret: ssh_key
    scripts:
      - cd /root/web/shop
      - docker-compose pull meichaofan/shop
      - docker-compose up

triger:
  branch:
    - master
  event:
    - push
