kind: pipeline
name: shop

workspace:
  base: /root
  path: web/shop/

steps:
  - name: build
    image: golang
    commands:
      - pwd
      - go env
      - go version
      - go build
    environment:
      GOPROXY: https://goproxy.io

  - name: publish
    image: plugins/docker
    commands:
      - docker login -u $USERNAME -p $PASSWORD
      - docker build meichaofan/shop .
      - docker push meichaofan/shop
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password

  - name: deploy
    image: appleboy/drone-ssh
    host:
      from_secret: host_ip
    username:
      from_secret: host_username
    port:
      from_secret: host_port
    secrets:
      from_secret: ssh_key
    script:
      - cd /root/web/shop
      - docker-compose pull meichaofan/shop
      - docker-compose up

triger:
  branch:
    - master
  event:
    - push